# Generated by Django 5.0.6 on 2026-05-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='safety_rating',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
