# Generated by Django 5.0.6 on 2026-05-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_safety_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
